import Head from "next/head";
import Footer from "../Footer";
import Header from "../Header";
import MobilMenu from "../MobilMenu";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Mas Humanos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <MobilMenu />
            <main>{children}</main>
            <Footer />
        </>
    );
};

export default Layout;
