import Head from 'next/head'
import ContactSection from '../components/ContactSection';
import HeroSection from '../components/HeroSection/'
import ServicesSection from '../components/ServicesSection';
import IconsSection from '../components/IconsSection';


const Home = ({ services }) => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <HeroSection />
        <ContactSection />
        <ServicesSection services={services} />
        <IconsSection />

      </main>

      <footer className="">

      </footer>
    </div>
  )
}
export async function getServerSideProps(context) {
  const res = await fetch(`http://localhost:3000/api/services`)
  const services = await res.json()
  return {
    props: {
      services
    },
  }
}
export default Home;
